a = input("Your name: ")
b = input("Your surname:")
print(("Your Full Name:",a+b))
a= int(input("enter first number:"))
b = int(input("enter second number:"))
print("addition:", {a+b})
print("subtraction:",{a-b})
print("multiplication:",{a*b})
print("division:",{a/b})
print("exponentiation:",{a**b})
print("floor division:",{a//b})
print("modulus:",{a%b})
print("less than:",{a<b})
print("greater than or equal to:",{a>=b})
print("not equal to:",{a!=b})
print("equal to:",{a==b})

# This code is a simple calculator that performs basic arithmetic operations and compares two numbers.